### ISSUE TITLE
ruby.wasm 2022-05-20-a 以降で動作しない

### ISSUE THREAD

**Issue by keyasuda** [keyasuda/bormashino#16]
```javascript
Uncaught (in promise) Error: <internal:/usr/local/lib/ruby/3.2.0+1/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rack
Did you mean?  racc (LoadError)
<internal:/usr/local/lib/ruby/3.2.0+1/rubygems/core_ext/kernel_require.rb>:85:in `require'
eval:4:in `<main>'
    at checkStatusTag (index.js:302:19)
    at evalRbCode (index.js:315:5)
    at RubyVM.eval (index.js:159:16)
    at Object.initVm (ruby.js:77:6)
    at async main (app.js:5:14)
```

**Comment by keyasuda** [comment]
2022-05-15-a では動くようになった。
2022-05-20-a で再度動かないように。
```
Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #8 module="rb-js-abi-host" function="rb-object-to-js-rb-value" error: function import requires a callable
    at Object.initVm (ruby.js:71:38)
    at async main (app.js:5:14)
initVm @ ruby.js:71
await in initVm (async)
5AKj5.bormashino @ app.js:31
newRequire @ index.e9bc9140.js:71
(anonymous) @ index.e9bc9140.js:122
(anonymous) @ index.e9bc9140.js:145
```
npmパッケージの変更が必要? cf. https://github.com/ruby/ruby.wasm/compare/2022-05-15-a...2022-05-20-a
